title: schalox's site
baseurl: ""

date_format: "%Y-%m-%d"

markdown:     redcarpet
permalink:    pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "schalox"

# vim: ts=2 sts=2 sw=2:
